In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])



In [3]:
print("Addition: \n", A + B)
print("Subtraction: \n", B - A)

C = 2 * A
print("Scalar Multiplication \n", C)


Addition: 
 [[ 6  8]
 [10 12]]
Subtraction: 
 [[4 4]
 [4 4]]
Scalar Multiplication 
 [[2 4]
 [6 8]]


In [4]:

result = np.dot(A, B)

print("Matrix Multiplication \n", result)

Matrix Multiplication 
 [[19 22]
 [43 50]]


In [6]:

I = np.eye(5)
print("Identity Matrix \n", I)

Z = np.zeros((2, 3))
# print("Zero Matrix \n", Z)

D = np.diag([1, 2, 3])
print("Diagonal Matrix\n", D)

Identity Matrix 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Matrix
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
