In [1]:
import numpy as np


In [2]:

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[9, 8], [7, 6]])

# Addition
print("Addition\n", A + B)

# Subtraction
print("Subtraction\n", A - B)

# Scalar Multiplication
print("Scalar Mult: \n", 3 * A)

Addition
 [[10 10]
 [10 10]]
Subtraction
 [[-8 -6]
 [-4 -2]]
Scalar Mult: 
 [[ 3  6]
 [ 9 12]]
