In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix: \n", matrix)

# Transpose
transpose = matrix.T
print("Transpose:\n", transpose)

another_matrix = np.array([[9,8,7], [6,5,4], [3,2,1]])
print("Addition: \n", matrix + another_matrix)
print("Multiplication : \n", matrix * another_matrix)

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication : 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
