In [1]:
import numpy as np


In [2]:
# Generate random dataset
dataset = np.random.randint(1, 51, size=(5,5))
print("Original: \n", dataset)

# Filter values > 25 and replace with 0
dataset[dataset > 25] = 0
print("Modified Dataset: \n", dataset)


# calculate summary stats
print("Sum: ", np.sum(dataset))
print("Mean: ", np.mean(dataset))
print("Standard Deviation: ", np.std(dataset))

Original: 
 [[48 44  2 48 30]
 [30 30 32 46 32]
 [24 19 36  8 37]
 [37 34 38 35 45]
 [ 6  8 39 23 31]]
Modified Dataset: 
 [[ 0  0  2  0  0]
 [ 0  0  0  0  0]
 [24 19  0  8  0]
 [ 0  0  0  0  0]
 [ 6  8  0 23  0]]
Sum:  90
Mean:  3.6
Standard Deviation:  7.238784428341543
