In [1]:
import numpy as np


In [2]:

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0 , -1])

result_add = matrix + vector
print("Add: \n", result_add)

result_mul = matrix * 2
print("Multiplication: \n", result_mul)

Add: 
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
Multiplication: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
