In [1]:
import numpy as np

A = np.array([[3, 1, 1], [-1, 3, 1], [1, 1, 3]])
U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:\n", S)
print("V Transpose:\n", Vt)

# Reconstruct
Sigma = np.zeros((3, 3))
np.fill_diagonal(Sigma, S)
reconstructed = U @ Sigma @ Vt
print("Reconstructed Matrix \n", reconstructed)

U:
 [[-0.57735027  0.57735027 -0.57735027]
 [-0.4412247  -0.81558342 -0.37435872]
 [-0.68701342  0.03860509  0.7256185 ]]
Singular Values:
 [4.48261292 3.17102979 1.68841687]
V Transpose:
 [[-0.4412247  -0.57735027 -0.68701342]
 [ 0.81558342 -0.57735027 -0.03860509]
 [-0.37435872 -0.57735027  0.7256185 ]]
Reconstructed Matrix 
 [[ 3.  1.  1.]
 [-1.  3.  1.]
 [ 1.  1.  3.]]
